import { LabTest, LabTemplate } from './types';

export const DEFAULT_TESTS: LabTest[] = [
  { id: "wbc", nameEn: "WBC", unit: "× 10³/μL", refRangeM: "4.5 - 11.0", refRangeF: "4.5 - 11.0", category: "hematology" },
  { id: "rbc", nameEn: "RBC", unit: "× 10⁶/μL", refRangeM: "4.5 - 5.9", refRangeF: "4.0 - 5.2", category: "hematology" },
  { id: "hemoglobin", nameEn: "Hemoglobin", unit: "g/dL", refRangeM: "13.5 - 17.5", refRangeF: "12.0 - 15.5", category: "hematology" },
  { id: "hematocrit", nameEn: "Hematocrit", unit: "%", refRangeM: "41 - 53", refRangeF: "36 - 46", category: "hematology" },
  { id: "mcv", nameEn: "MCV", unit: "fL", refRangeM: "80 - 100", refRangeF: "80 - 100", category: "hematology" },
  { id: "mch", nameEn: "MCH", unit: "pg", refRangeM: "27 - 33", refRangeF: "27 - 33", category: "hematology" },
  { id: "mchc", nameEn: "MCHC", unit: "g/dL", refRangeM: "32 - 36", refRangeF: "32 - 36", category: "hematology" },
  { id: "platelets", nameEn: "Platelets", unit: "× 10³/μL", refRangeM: "150 - 400", refRangeF: "150 - 400", category: "hematology" },
  { id: "neutrophils", nameEn: "Neutrophils %", unit: "%", refRangeM: "50 - 70", refRangeF: "50 - 70", category: "hematology" },
  { id: "lymphocytes", nameEn: "Lymphocytes %", unit: "%", refRangeM: "20 - 40", refRangeF: "20 - 40", category: "hematology" },
  { id: "monocytes", nameEn: "Monocytes %", unit: "%", refRangeM: "2 - 8", refRangeF: "2 - 8", category: "hematology" },
  { id: "eosinophils", nameEn: "Eosinophils %", unit: "%", refRangeM: "1 - 4", refRangeF: "1 - 4", category: "hematology" },
  { id: "basophils", nameEn: "Basophils %", unit: "%", refRangeM: "0 - 1", refRangeF: "0 - 1", category: "hematology" },
  { id: "esr", nameEn: "ESR", unit: "mm/hr", refRangeM: "0 - 15", refRangeF: "0 - 20", category: "hematology" },
  { id: "reticulocytes", nameEn: "Reticulocytes", unit: "%", refRangeM: "0.5 - 1.5", refRangeF: "0.5 - 1.5", category: "hematology" },
  { id: "fasting_blood_sugar", nameEn: "Fasting Blood Sugar", unit: "mg/dL", refRangeM: "70 - 100", refRangeF: "70 - 100", category: "biochemistry" },
  { id: "random_blood_sugar", nameEn: "Random Blood Sugar", unit: "mg/dL", refRangeM: "70 - 140", refRangeF: "70 - 140", category: "biochemistry" },
  { id: "post_prandial_blood_sugar", nameEn: "Post Prandial Blood Sugar", unit: "mg/dL", refRangeM: "< 140", refRangeF: "< 140", category: "biochemistry" },
  { id: "hba1c", nameEn: "HbA1c", unit: "%", refRangeM: "4.0 - 5.6", refRangeF: "4.0 - 5.6", category: "biochemistry" },
  { id: "total_cholesterol", nameEn: "Total Cholesterol", unit: "mg/dL", refRangeM: "< 200", refRangeF: "< 200", category: "biochemistry" },
  { id: "triglycerides", nameEn: "Triglycerides", unit: "mg/dL", refRangeM: "< 150", refRangeF: "< 150", category: "biochemistry" },
  { id: "hdl_cholesterol", nameEn: "HDL Cholesterol", unit: "mg/dL", refRangeM: "> 40", refRangeF: "> 50", category: "biochemistry" },
  { id: "ldl_cholesterol", nameEn: "LDL Cholesterol", unit: "mg/dL", refRangeM: "< 100", refRangeF: "< 100", category: "biochemistry" },
  { id: "vldl_cholesterol", nameEn: "VLDL Cholesterol", unit: "mg/dL", refRangeM: "2 - 30", refRangeF: "2 - 30", category: "biochemistry" },
  { id: "urea", nameEn: "Urea", unit: "mg/dL", refRangeM: "15 - 45", refRangeF: "15 - 45", category: "biochemistry" },
  { id: "creatinine", nameEn: "Creatinine", unit: "mg/dL", refRangeM: "0.7 - 1.3", refRangeF: "0.6 - 1.1", category: "biochemistry" },
  { id: "bun", nameEn: "BUN", unit: "mg/dL", refRangeM: "7 - 20", refRangeF: "7 - 20", category: "biochemistry" },
  { id: "uric_acid", nameEn: "Uric Acid", unit: "mg/dL", refRangeM: "3.4 - 7.0", refRangeF: "2.4 - 6.0", category: "biochemistry" },
  { id: "calcium", nameEn: "Calcium", unit: "mg/dL", refRangeM: "8.5 - 10.5", refRangeF: "8.5 - 10.5", category: "biochemistry" },
  { id: "phosphorus", nameEn: "Phosphorus", unit: "mg/dL", refRangeM: "2.5 - 4.5", refRangeF: "2.5 - 4.5", category: "biochemistry" },
  { id: "sodium", nameEn: "Sodium", unit: "mEq/L", refRangeM: "135 - 145", refRangeF: "135 - 145", category: "biochemistry" },
  { id: "potassium", nameEn: "Potassium", unit: "mEq/L", refRangeM: "3.5 - 5.0", refRangeF: "3.5 - 5.0", category: "biochemistry" },
  { id: "chloride", nameEn: "Chloride", unit: "mEq/L", refRangeM: "98 - 106", refRangeF: "98 - 106", category: "biochemistry" },
  { id: "magnesium", nameEn: "Magnesium", unit: "mg/dL", refRangeM: "1.7 - 2.2", refRangeF: "1.7 - 2.2", category: "biochemistry" },
  { id: "total_protein", nameEn: "Total Protein", unit: "g/dL", refRangeM: "6.0 - 8.3", refRangeF: "6.0 - 8.3", category: "biochemistry" },
  { id: "albumin", nameEn: "Albumin", unit: "g/dL", refRangeM: "3.5 - 5.0", refRangeF: "3.5 - 5.0", category: "biochemistry" },
  { id: "globulin", nameEn: "Globulin", unit: "g/dL", refRangeM: "2.3 - 3.4", refRangeF: "2.3 - 3.4", category: "biochemistry" },
  { id: "total_bilirubin", nameEn: "Total Bilirubin", unit: "mg/dL", refRangeM: "0.1 - 1.2", refRangeF: "0.1 - 1.2", category: "biochemistry" },
  { id: "direct_bilirubin", nameEn: "Direct Bilirubin", unit: "mg/dL", refRangeM: "0.0 - 0.3", refRangeF: "0.0 - 0.3", category: "biochemistry" },
  { id: "indirect_bilirubin", nameEn: "Indirect Bilirubin", unit: "mg/dL", refRangeM: "0.2 - 0.8", refRangeF: "0.2 - 0.8", category: "biochemistry" },
  { id: "ast", nameEn: "AST", unit: "U/L", refRangeM: "10 - 40", refRangeF: "9 - 32", category: "biochemistry" },
  { id: "alt", nameEn: "ALT", unit: "U/L", refRangeM: "10 - 40", refRangeF: "7 - 35", category: "biochemistry" },
  { id: "alp", nameEn: "ALP", unit: "U/L", refRangeM: "44 - 147", refRangeF: "44 - 147", category: "biochemistry" },
  { id: "ggt", nameEn: "GGT", unit: "U/L", refRangeM: "8 - 61", refRangeF: "5 - 36", category: "biochemistry" },
  { id: "ldh", nameEn: "LDH", unit: "U/L", refRangeM: "140 - 280", refRangeF: "140 - 280", category: "biochemistry" },
  { id: "amylase", nameEn: "Amylase", unit: "U/L", refRangeM: "23 - 85", refRangeF: "23 - 85", category: "biochemistry" },
  { id: "lipase", nameEn: "Lipase", unit: "U/L", refRangeM: "0 - 160", refRangeF: "0 - 160", category: "biochemistry" },
  { id: "serum_iron", nameEn: "Serum Iron", unit: "μg/dL", refRangeM: "65 - 176", refRangeF: "50 - 170", category: "biochemistry" },
  { id: "tibc",nameEn: "TIBC", unit: "μg/dL", refRangeM: "240 - 450", refRangeF: "240 - 450", category: "biochemistry" },
  { id: "ferritin", nameEn: "Ferritin", unit: "ng/mL", refRangeM: "20 - 250", refRangeF: "10 - 120", category: "biochemistry" },
  { id: "tsh", nameEn: "TSH", unit: "mIU/L", refRangeM: "0.4 - 4.0", refRangeF: "0.4 - 4.0", category: "endocrinology" },
  { id: "total_t3", nameEn: "Total T3", unit: "ng/dL", refRangeM: "80 - 200", refRangeF: "80 - 200", category: "endocrinology" },
  { id: "total_t4", nameEn: "Total T4", unit: "μg/dL", refRangeM: "5.0 - 12.0", refRangeF: "5.0 - 12.0", category: "endocrinology" },
  { id: "free_t3", nameEn: "Free T3", unit: "pg/mL", refRangeM: "2.3 - 4.2", refRangeF: "2.3 - 4.2", category: "endocrinology" },
  { id: "free_t4", nameEn: "Free T4", unit: "ng/dL", refRangeM: "0.8 - 1.8", refRangeF: "0.8 - 1.8", category: "endocrinology" },
  { id: "prolactin", nameEn: "Prolactin", unit: "ng/mL", refRangeM: "2 - 18", refRangeF: "2 - 29", category: "endocrinology" },
  { id: "lh", nameEn: "LH", unit: "mIU/mL", refRangeM: "1.7 - 8.6", refRangeF: "1.0 - 11.4", category: "endocrinology" },
  { id: "fsh", nameEn: "FSH", unit: "mIU/mL", refRangeM: "1.5 - 12.4", refRangeF: "1.7 - 21.5", category: "endocrinology" },
  { id: "testosterone", nameEn: "Testosterone", unit: "ng/dL", refRangeM: "300 - 1000", refRangeF: "15 - 70", category: "endocrinology" },
  { id: "vitamin_d3", nameEn: "Vitamin D3", unit: "ng/mL", refRangeM: "30 - 100", refRangeF: "30 - 100", category: "endocrinology" },
  { id: "vitamin_b12", nameEn: "Vitamin B12", unit: "pg/mL", refRangeM: "200 - 900", refRangeF: "200 - 900", category: "endocrinology" },
  { id: "crp", nameEn: "CRP", unit: "mg/L", refRangeM: "< 5", refRangeF: "< 5", category: "serology" },
  { id: "aso", nameEn: "ASO", unit: "IU/mL", refRangeM: "< 200", refRangeF: "< 200", category: "serology" },
  { id: "rheumatoid_factor", nameEn: "Rheumatoid Factor", unit: "IU/mL", refRangeM: "< 14", refRangeF: "< 14", category: "serology" },
  { id: "widal_test_o", nameEn: "Widal Test O", unit: "Titer", refRangeM: "< 1/80", refRangeF: "< 1/80", category: "serology" },
  { id: "widal_test_h", nameEn: "Widal Test H", unit: "Titer", refRangeM: "< 1/80", refRangeF: "< 1/80", category: "serology" },
  { id: "hbsag", nameEn: "HBsAg", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "serology" },
  { id: "hcv_ab", nameEn: "HCV Ab", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "serology" },
  { id: "hiv_12", nameEn: "HIV 1/2", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "serology" },
  { id: "vdrl", nameEn: "VDRL", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "serology" },
  { id: "pregnancy_test", nameEn: "Pregnancy Test", unit: "Result", refRangeM: "-", refRangeF: "Negative", category: "serology" },
  { id: "urine_color", nameEn: "Urine Color", unit: "Result", refRangeM: "Yellow", refRangeF: "Yellow", category: "urinalysis" },
  { id: "urine_appearance", nameEn: "Urine Appearance", unit: "Result", refRangeM: "Clear", refRangeF: "Clear", category: "urinalysis" },
  { id: "specific_gravity", nameEn: "Specific Gravity", unit: "Result", refRangeM: "1.005-1.030", refRangeF: "1.005-1.030", category: "urinalysis" },
  { id: "ph", nameEn: "pH", unit: "Result", refRangeM: "4.6 - 8.0", refRangeF: "4.6 - 8.0", category: "urinalysis" },
  { id: "urine_protein", nameEn: "Urine Protein", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "urine_glucose", nameEn: "Urine Glucose", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "urine_ketones", nameEn: "Urine Ketones", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "urine_blood", nameEn: "Urine Blood", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "urine_bilirubin", nameEn: "Urine Bilirubin", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "urobilinogen", nameEn: "Urobilinogen", unit: "Result", refRangeM: "Normal", refRangeF: "Normal", category: "urinalysis" },
  { id: "urine_nitrite", nameEn: "Urine Nitrite", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "urine_leukocytes", nameEn: "Urine Leukocytes", unit: "Result", refRangeM: "Negative", refRangeF: "Negative", category: "urinalysis" },
  { id: "pus_cells", nameEn: "Pus Cells", unit: "/HPF", refRangeM: "0 - 5", refRangeF: "0 - 5", category: "urinalysis" },
  { id: "rbcs", nameEn: "RBCs", unit: "/HPF", refRangeM: "0 - 2", refRangeF: "0 - 2", category: "urinalysis" },
  { id: "epithelial_cells", nameEn: "Epithelial Cells", unit: "/HPF", refRangeM: "Few", refRangeF: "Few", category: "urinalysis" },
  { id: "crystals", nameEn: "Crystals", unit: "Result", refRangeM: "Nil", refRangeF: "Nil", category: "urinalysis" },
  { id: "casts", nameEn: "Casts", unit: "Result", refRangeM: "Nil", refRangeF: "Nil", category: "urinalysis" },
  { id: "bacteria", nameEn: "Bacteria", unit: "Result", refRangeM: "Nil", refRangeF: "Nil", category: "urinalysis" },
  { id: "yeast", nameEn: "Yeast", unit: "Result", refRangeM: "Nil", refRangeF: "Nil", category: "urinalysis" }
];

export const DEFAULT_TEMPLATES: LabTemplate[] = [
  {
    id: "cbc",
    nameEn: "Complete Blood Count (CBC)",
    nameAr: "صورة الدم الكاملة (CBC)",
    category: "hematology",
    items: [
      { id: "wbc", nameEn: "WBC", unit: "10^3/uL", refRangeM: "4.0 - 11.0", refRangeF: "4.0 - 11.0" },
      { id: "rbc", nameEn: "RBC", unit: "10^6/uL", refRangeM: "4.5 - 5.9", refRangeF: "4.1 - 5.1" },
      { id: "hemoglobin", nameEn: "Hemoglobin", unit: "g/dL", refRangeM: "13.5 - 17.5", refRangeF: "12.0 - 15.5" },
      { id: "hematocrit", nameEn: "Hematocrit", unit: "%", refRangeM: "41 - 53", refRangeF: "36 - 46" },
      { id: "mcv", nameEn: "MCV", unit: "fL", refRangeM: "80 - 100", refRangeF: "80 - 100" },
      { id: "mch", nameEn: "MCH", unit: "pg", refRangeM: "27 - 33", refRangeF: "27 - 33" },
      { id: "mchc", nameEn: "MCHC", unit: "g/dL", refRangeM: "32 - 36", refRangeF: "32 - 36" },
      { id: "platelets", nameEn: "Platelets (PLT)", unit: "10^3/uL", refRangeM: "150 - 450", refRangeF: "150 - 450" },
      { id: "neutrophils", nameEn: "Neutrophils %", unit: "%", refRangeM: "40 - 74", refRangeF: "40 - 74" },
      { id: "lymphocytes", nameEn: "Lymphocytes %", unit: "%", refRangeM: "19 - 48", refRangeF: "19 - 48" },
      { id: "monocytes", nameEn: "Monocytes %", unit: "%", refRangeM: "3.4 - 9.0", refRangeF: "3.4 - 9.0" },
      { id: "eosinophils", nameEn: "Eosinophils %", unit: "%", refRangeM: "0 - 7", refRangeF: "0 - 7" },
      { id: "basophils", nameEn: "Basophils %", unit: "%", refRangeM: "0 - 1.5", refRangeF: "0 - 1.5" },
      { id: "esr", nameEn: "ESR", unit: "mm/hr", refRangeM: "0 - 15", refRangeF: "0 - 20" },
      { id: "reticulocytes", nameEn: "Reticulocytes", unit: "%", refRangeM: "0.5 - 2.5", refRangeF: "0.5 - 2.5" }
    ]
  },
  {
    id: "lipid",
    nameEn: "Lipid Profile",
    nameAr: "ملف الدهون كامل (Lipid Profile)",
    category: "biochemistry",
    items: [
      { id: "total_cholesterol", nameEn: "Total Cholesterol", unit: "mg/dL", refRangeM: "< 200", refRangeF: "< 200" },
      { id: "triglycerides", nameEn: "Triglycerides", unit: "mg/dL", refRangeM: "< 150", refRangeF: "< 150" },
      { id: "hdl_cholesterol", nameEn: "HDL Cholesterol", unit: "mg/dL", refRangeM: "> 40", refRangeF: "> 50" },
      { id: "ldl_cholesterol", nameEn: "LDL Cholesterol", unit: "mg/dL", refRangeM: "< 100", refRangeF: "< 100" },
      { id: "vldl_cholesterol", nameEn: "VLDL Cholesterol", unit: "mg/dL", refRangeM: "2 - 30", refRangeF: "2 - 30" }
    ]
  },
  {
    id: "lft",
    nameEn: "Liver Function Tests (LFT)",
    nameAr: "وظائف الكبد (LFT)",
    category: "biochemistry",
    items: [
      { id: "alt", nameEn: "ALT (SGPT)", unit: "U/L", refRangeM: "7 - 56", refRangeF: "7 - 45" },
      { id: "ast", nameEn: "AST (SGOT)", unit: "U/L", refRangeM: "10 - 40", refRangeF: "10 - 35" },
      { id: "alp", nameEn: "ALP", unit: "U/L", refRangeM: "44 - 147", refRangeF: "44 - 147" },
      { id: "ggt", nameEn: "GGT", unit: "U/L", refRangeM: "8 - 61", refRangeF: "5 - 36" },
      { id: "total_bilirubin", nameEn: "Total Bilirubin", unit: "mg/dL", refRangeM: "0.2 - 1.2", refRangeF: "0.2 - 1.2" },
      { id: "direct_bilirubin", nameEn: "Direct Bilirubin", unit: "mg/dL", refRangeM: "0.0 - 0.3", refRangeF: "0.0 - 0.3" },
      { id: "indirect_bilirubin", nameEn: "Indirect Bilirubin", unit: "mg/dL", refRangeM: "0.2 - 0.8", refRangeF: "0.2 - 0.8" },
      { id: "total_protein", nameEn: "Total Protein", unit: "g/dL", refRangeM: "6.3 - 8.2", refRangeF: "6.3 - 8.2" },
      { id: "albumin", nameEn: "Albumin", unit: "g/dL", refRangeM: "3.5 - 5.0", refRangeF: "3.5 - 5.0" },
      { id: "globulin", nameEn: "Globulin", unit: "g/dL", refRangeM: "2.0 - 3.5", refRangeF: "2.0 - 3.5" }
    ]
  },
  {
    id: "rft",
    nameEn: "Renal Function Tests (RFT)",
    nameAr: "وظائف الكلى (RFT)",
    category: "biochemistry",
    items: [
      { id: "creatinine", nameEn: "Creatinine", unit: "mg/dL", refRangeM: "0.7 - 1.3", refRangeF: "0.5 - 1.1" },
      { id: "urea", nameEn: "Urea", unit: "mg/dL", refRangeM: "15 - 45", refRangeF: "15 - 45" },
      { id: "bun", nameEn: "BUN", unit: "mg/dL", refRangeM: "7 - 25", refRangeF: "7 - 25" },
      { id: "uric_acid", nameEn: "Uric Acid", unit: "mg/dL", refRangeM: "3.4 - 7.0", refRangeF: "2.4 - 6.0" }
    ]
  },
  {
    id: "tft",
    nameEn: "Thyroid Function Tests (TFT)",
    nameAr: "هرمونات الغدة الدرقية (TFT)",
    category: "endocrinology",
    items: [
      { id: "tsh", nameEn: "TSH", unit: "mIU/L", refRangeM: "0.4 - 4.0", refRangeF: "0.4 - 4.0" },
      { id: "free_t3", nameEn: "Free T3", unit: "pg/mL", refRangeM: "2.3 - 4.2", refRangeF: "2.3 - 4.2" },
      { id: "free_t4", nameEn: "Free T4", unit: "ng/dL", refRangeM: "0.8 - 1.8", refRangeF: "0.8 - 1.8" }
    ]
  },
  {
    id: "widal",
    nameEn: "Widal Test (Typhoid)",
    nameAr: "فحص التيفوئيد (Widal Test)",
    category: "serology",
    items: [
      { id: "widal_test_o", nameEn: "Widal Test O", unit: "Titer", refRangeM: "< 1/80", refRangeF: "< 1/80" },
      { id: "widal_test_h", nameEn: "Widal Test H", unit: "Titer", refRangeM: "< 1/80", refRangeF: "< 1/80" }
    ]
  },
  {
    id: "urine",
    nameEn: "Urine Analysis",
    nameAr: "تحليل البول الكامل (Urine Analysis)",
    category: "urinalysis",
    items: [
      { id: "urine_color", nameEn: "Urine Color", unit: "Result", refRangeM: "Yellow", refRangeF: "Yellow" },
      { id: "urine_appearance", nameEn: "Urine Appearance", unit: "Result", refRangeM: "Clear", refRangeF: "Clear" },
      { id: "ph", nameEn: "pH", unit: "Result", refRangeM: "4.6 - 8.0", refRangeF: "4.6 - 8.0" },
      { id: "urine_protein", nameEn: "Urine Protein", unit: "Result", refRangeM: "Negative", refRangeF: "Negative" },
      { id: "urine_glucose", nameEn: "Urine Glucose", unit: "Result", refRangeM: "Negative", refRangeF: "Negative" },
      { id: "pus_cells", nameEn: "Pus Cells", unit: "/HPF", refRangeM: "0 - 5", refRangeF: "0 - 5" },
      { id: "rbcs", nameEn: "RBCs", unit: "/HPF", refRangeM: "0 - 2", refRangeF: "0 - 2" }
    ]
  }
];
